name: ghaction
description: "GitHub Action Spike: Action"
runs:
  using: "composite"
  steps:
    - name: Hello
      run: echo "Hello World!"
      shell: bash
    - uses: actions/checkout@v4
      with:
        repository: rlipscombe/ghaction
        ref: main
    - run: cat hello.txt
      shell: bash
